### ISSUE TITLE
Forks and modifications 

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/querygarden#3]
@MaximMoinat I saw that you made a fork of this repo, are you planning a PR?

**Comment by MaximMoinat** [comment]
No, I was just exploring your repo.

By the way: where do you host the source for the QueryGarden github.io page? https://jpfairbanks.github.io/querygarden/

**Comment by jpfairbanks** [comment]
https://github.com/jpfairbanks/querygarden/tree/master/docs
