### ISSUE TITLE
Incorrect import

### ISSUE THREAD

**Issue by mehalter** [jpfairbanks/querygarden#4]
`"github.com/Sirupsen/logrus"` should be `"github.com/sirupsen/logrus"`

https://github.com/jpfairbanks/querygarden/blob/a95113ea1431c95dd9fc99b6679a2fefc056a4f8/log/log.go#L6

**Comment by mehalter** [comment]
This breaks go compiling the module for whatever reason

**Comment by tgoodyear** [comment]
Workaround available but not ideal.
```
go mod edit -replace github.com/Sirupsen/logrus@v1.7.1=github.com/sirupsen/logrus@v1.7.1
```

**Comment by jpfairbanks** [comment]
Merged!
